### ISSUE TITLE
Does not build on Mac OS X Darwin

### ISSUE THREAD

**Issue by teivah** [enola-dev/enola#246] opened 2023-06-23 11:41 UTC
## Expected Behavior

Running `test.bash` should return a success

## Actual Behavior

```
$ ./test.bash                            
$ b test //...
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @bazel_tools~cc_configure_extension~local_config_cc//:toolchain: cc_toolchain_suite '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin'
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: Analysis of target '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' failed
ERROR: Analysis of target '//core/lib:core_buf_proto_lint' failed; build aborted: 
INFO: Elapsed time: 5.855s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching repository @rules_jvm_external~5.2; starting
    Fetching repository @rules_java~5.3.5~toolchains~remote_java_tools; starting
    Fetching repository @rules_java~5.3.5~toolchains~remotejdk11_macos; starting
```

## Steps to Reproduce the Problem

1. Run `test.bash` on a Mac OS machine

## Specifications

- Platform: Mac M1 (ARM)

**Comment by vorburger** [comment] 2023-06-23 11:55
Looking at e.g. https://github.com/bazelbuild/examples/tree/main/cpp-tutorial/stage1 does not mention that a Toolchain has to be manually configured on Mac to build C++ with Bazel. 

So this seems to be specifically related either to one of the _Bazel modules_ which this project uses. I would like to narrow down which one... is it specific (and only) affecting the https://rules-proto-grpc.com stuff, as the error above mentions, or does it also affect the existing "basic" Java & Go Proto generation?

@teivah could you post the output when you run the following commands:

* `bazelisk build //core/lib:core_proto`
* `bazelisk build //core/lib:core_java_proto`
* `bazelisk build //core/lib:core_java_grpc`
* `bazelisk build //core/lib:core_go_proto`

**Comment by teivah** [comment] 2023-06-23 11:58
```
➜  enola git:(main) ✗ bazelisk build //core/lib:core_proto
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @bazel_tools~cc_configure_extension~local_config_cc//:toolchain: cc_toolchain_suite '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin'
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: Analysis of target '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' failed
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/protobuf~3.19.6/BUILD:513:10: errors encountered resolving select() keys for @protobuf~3.19.6//:protoc
ERROR: Analysis of target '//core/lib:core_proto' failed; build aborted: 
INFO: Elapsed time: 16.677s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (69 packages loaded, 351 targets configured)

➜  enola git:(main) ✗ bazelisk build //core/lib:core_java_proto
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @bazel_tools~cc_configure_extension~local_config_cc//:toolchain: cc_toolchain_suite '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin'
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: Analysis of target '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' failed
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/protobuf~3.19.6/BUILD:513:10: errors encountered resolving select() keys for @protobuf~3.19.6//:protoc
ERROR: Analysis of target '//core/lib:core_java_proto' failed; build aborted: 
INFO: Elapsed time: 0.632s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 4 targets configured)

➜  enola git:(main) ✗ bazelisk build //core/lib:core_java_grpc
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @bazel_tools~cc_configure_extension~local_config_cc//:toolchain: cc_toolchain_suite '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin'
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: Analysis of target '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' failed
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/protobuf~3.19.6/BUILD:513:10: errors encountered resolving select() keys for @protobuf~3.19.6//:protoc
ERROR: Analysis of target '//core/lib:core_java_grpc' failed; build aborted: 
INFO: Elapsed time: 0.534s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 1 target configured)
    currently loading: @com_google_protobuf//build_defs

➜  enola git:(main) ✗ bazelisk build //core/lib:core_go_proto
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @bazel_tools~cc_configure_extension~local_config_cc//:toolchain: cc_toolchain_suite '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin'
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/bazel_tools~cc_configure_extension~local_config_cc/BUILD:48:19: Analysis of target '@bazel_tools~cc_configure_extension~local_config_cc//:toolchain' failed
ERROR: /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/external/protobuf~3.19.6/BUILD:513:10: errors encountered resolving select() keys for @protobuf~3.19.6//:protoc
ERROR: Analysis of target '//core/lib:core_go_proto' failed; build aborted: 
INFO: Elapsed time: 2.676s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 587 targets configured)
    Fetching https://bcr.bazel.build/bazel_registry.json
```

**Comment by vorburger** [comment] 2023-06-23 12:00
The above "proves" (I think) that this has nothing to do e.g. with https://rules-proto-grpc.com/ specifically, and that its stuck with the (basic) `@protobuf~3.19.6//:protoc` already.

> Looking at e.g. https://github.com/bazelbuild/examples/tree/main/cpp-tutorial/stage1 does not mention that a Toolchain has to be manually configured on Mac to build C++ with Bazel.

Actually, just to be extra double sure, would you mind to try to run that on (your) Mac?

**Comment by teivah** [comment] 2023-06-23 12:07
All good

```
➜  stage1 git:(main) bazel build //main:hello-world

Starting local Bazel server and connecting to it...
INFO: Analyzed target //main:hello-world (36 packages loaded, 161 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 9.931s, Critical Path: 0.65s
INFO: 8 processes: 6 internal, 2 darwin-sandbox.
INFO: Build completed successfully, 8 total actions
```

**Comment by vorburger** [comment] 2023-06-23 12:23
In that case, let's try out a totally trivial simple standalone project with JUST a `proto_library`:

Does https://github.com/vorburger/LearningBazel/tree/develop/proto_library work on (your) Mac?

**Comment by vorburger** [comment] 2023-06-23 12:36
> Does https://github.com/vorburger/LearningBazel/tree/develop/proto_library work on (your) Mac?

@teivah confirmed that it does. So it's something particular to this project.

This seems like a good opportunity to do some clean-up, and tentatively remove `rules-proto-grpc` as a simplification, to see if that could help for this...

**Comment by teivah** [comment] 2023-06-23 13:54
I'm finally able to run `./test.bash`. Here are the steps I followed:
1. Installing Xcode
1. Running `bazel clean --expunge` ([source](https://github.com/bazelbuild/bazel/issues/9303#issuecomment-603346106))

**Comment by vorburger** [comment] 2023-06-23 14:00
Cool!! And you mentioned there are some Java test failures - let's keep this issue open to address those.

**Comment by teivah** [comment] 2023-06-23 14:08
Yes, sorry, here's the exact log:

```
➜  enola git:(main) ✗ ./test.bash
$ b test //...
INFO: Analyzed 67 targets (359 packages loaded, 15296 targets configured).
INFO: Found 30 targets and 37 test targets...
INFO: From Testing //common/common:src/test/java/dev/enola/common/io/mediatype/MediaTypeDetectorTest:
==================== Test output for //common/common:src/test/java/dev/enola/common/io/mediatype/MediaTypeDetectorTest:
JUnit4 Test Runner
.E
Time: 0.306
There was 1 failure:
1) testDetect(dev.enola.common.io.mediatype.MediaTypeDetectorTest)
value of: detect(...)
expected: application/yaml; charset=utf-8
but was : application/x-yaml
        at dev.enola.common.io.mediatype.MediaTypeDetectorTest.testDetect(MediaTypeDetectorTest.java:55)

FAILURES!!!
Tests run: 1,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2023-06-23 13:49:33 --

================================================================================
INFO: From Testing //common/markdown:src/test/java/dev/enola/common/markdown/exec/RunnerTest:
==================== Test output for //common/markdown:src/test/java/dev/enola/common/markdown/exec/RunnerTest:
JUnit4 Test Runner
.[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [/usr/bin/env, bash, -c, does-not-exist] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
[Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - env: bash: does-not-exist: command not found
[Exec Default Executor] INFO ch.vorburger.exec.LoggingExecuteResultHandler - Program [/usr/bin/env, bash, -c, does-not-exist] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.) just exited, with value 127
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait max. 3000ms for process to terminate itself: Program [/usr/bin/env, bash, -c, does-not-exist] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
E.[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [/usr/bin/env, bash, -c, false] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
[Exec Default Executor] INFO ch.vorburger.exec.LoggingExecuteResultHandler - Program [/usr/bin/env, bash, -c, false] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.) just exited, with value 1
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait max. 3000ms for process to terminate itself: Program [/usr/bin/env, bash, -c, false] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
.[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [/usr/bin/env, bash, -c, echo hi] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - env: hi
[Exec Default Executor] INFO ch.vorburger.exec.LoggingExecuteResultHandler - Program [/usr/bin/env, bash, -c, echo hi] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.) just exited, with value 0
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait max. 3000ms for process to terminate itself: Program [/usr/bin/env, bash, -c, echo hi] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
.[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [/usr/bin/env, bash, -c, true] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)
[Exec Default Executor] INFO ch.vorburger.exec.LoggingExecuteResultHandler - Program [/usr/bin/env, bash, -c, true] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.) just exited, with value 0
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait max. 3000ms for process to terminate itself: Program [/usr/bin/env, bash, -c, true] (in working directory /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/sandbox/darwin-sandbox/2/execroot/_main/bazel-out/darwin-fastbuild/bin/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest.runfiles/_main/.)

Time: 0.521
There was 1 failure:
1) testInexistantCommand(dev.enola.common.markdown.exec.RunnerTest)
org.junit.ComparisonFailure: expected:<bash: [line 1: ]does-not-exist: comm...> but was:<bash: []does-not-exist: comm...>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at dev.enola.common.markdown.exec.RunnerTest.check(RunnerTest.java:35)
        at dev.enola.common.markdown.exec.RunnerTest.testInexistantCommand(RunnerTest.java:56)

FAILURES!!!
Tests run: 4,  Failures: 1


BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2023-06-23 13:49:34 --

================================================================================
INFO: Elapsed time: 19.125s, Critical Path: 3.03s
INFO: 3 processes: 1 internal, 2 darwin-sandbox.
INFO: Build completed, 2 tests FAILED, 3 total actions
//:shellcheck_test                                              (cached) PASSED in 2.4s
//cli:src/test/java/dev/enola/cli/EnolaTest                     (cached) PASSED in 14.2s
//common/common:src/test/java/dev/enola/common/io/mediatype/MediaTypesTest (cached) PASSED in 1.9s
//common/common:src/test/java/dev/enola/common/io/resource/ClasspathUrlResourceTest (cached) PASSED in 2.6s
//common/common:src/test/java/dev/enola/common/io/resource/EmptyResourceTest (cached) PASSED in 2.2s
//common/common:src/test/java/dev/enola/common/io/resource/ErrorResourceTest (cached) PASSED in 2.3s
//common/common:src/test/java/dev/enola/common/io/resource/FileDescriptorResourceTest (cached) PASSED in 1.7s
//common/common:src/test/java/dev/enola/common/io/resource/FileResourceTest (cached) PASSED in 1.6s
//common/common:src/test/java/dev/enola/common/io/resource/HttpUrlResourceTest (cached) PASSED in 1.8s
//common/common:src/test/java/dev/enola/common/io/resource/MemoryResourceTest (cached) PASSED in 2.0s
//common/common:src/test/java/dev/enola/common/io/resource/NullResourceTest (cached) PASSED in 2.1s
//common/common:src/test/java/dev/enola/common/io/resource/ReplacingResourceTest (cached) PASSED in 1.8s
//common/common:src/test/java/dev/enola/common/io/resource/ResourceProvidersTest (cached) PASSED in 2.5s
//common/common:src/test/java/dev/enola/common/io/resource/StringResourceTest (cached) PASSED in 1.8s
//common/common:src/test/java/dev/enola/common/io/resource/URIsTest (cached) PASSED in 2.2s
//common/common:src/test/java/dev/enola/common/protobuf/ProtobufMediaTypesTest (cached) PASSED in 2.0s
//common/markdown:src/test/java/dev/enola/common/markdown/exec/ExecMDTest (cached) PASSED in 2.8s
//common/protobuf:src/test/java/dev/enola/common/protobuf/MessageValidatorTest (cached) PASSED in 1.8s
//common/protobuf:src/test/java/dev/enola/common/protobuf/ProtoIOTest (cached) PASSED in 3.1s
//common/yamljson:src/test/java/dev/enola/common/yamljson/YamlJsonTest (cached) PASSED in 2.3s
//connectors/demo:src/test/java/dev/enola/demo/ServerTest       (cached) PASSED in 4.8s
//core/impl:src/test/java/dev/enola/core/EntityServiceProviderTest (cached) PASSED in 4.5s
//core/impl:src/test/java/dev/enola/core/EntityTest             (cached) PASSED in 3.2s
//core/impl:src/test/java/dev/enola/core/grpc/EnolaGrpcServerTest (cached) PASSED in 4.3s
//core/impl:src/test/java/dev/enola/core/meta/EntityKindRepositoryTest (cached) PASSED in 3.7s
//core/impl:src/test/java/dev/enola/core/meta/EntityKindValidationsTest (cached) PASSED in 2.8s
//core/impl:src/test/java/dev/enola/core/meta/docgen/MarkdownDocGeneratorTest (cached) PASSED in 2.8s
//core/impl:src/test/java/dev/enola/core/meta/docgen/StringUtilTest (cached) PASSED in 2.3s
//core/impl:src/test/java/dev/enola/core/tbd/RosettaTest        (cached) PASSED in 3.3s
//core/lib:core_buf_proto_lint                                  (cached) PASSED in 1.6s
//core/lib:src/test/java/dev/enola/core/IDsTest                 (cached) PASSED in 2.0s
//web/rest:src/test/java/dev/enola/web/rest/RestTest            (cached) PASSED in 7.0s
//web/sun:src/test/java/dev/enola/web/sun/test/SunServerTest    (cached) PASSED in 3.3s
//web/ui-soy:src/test/java/dev/enola/web/ui/SoyTest             (cached) PASSED in 3.4s
//web/ui-soy:src/test/java/dev/enola/web/ui/UiTest              (cached) PASSED in 7.8s
//common/common:src/test/java/dev/enola/common/io/mediatype/MediaTypeDetectorTest FAILED in 1.2s
  /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/execroot/_main/bazel-out/darwin-fastbuild/testlogs/common/common/src/test/java/dev/enola/common/io/mediatype/MediaTypeDetectorTest/test.log
//common/markdown:src/test/java/dev/enola/common/markdown/exec/RunnerTest FAILED in 1.3s
  /private/var/tmp/_bazel_teivah/160bc262a2ae7f2d9573f4b3dad216bd/execroot/_main/bazel-out/darwin-fastbuild/testlogs/common/markdown/src/test/java/dev/enola/common/markdown/exec/RunnerTest/test.log

Executed 2 out of 37 tests: 35 tests pass and 2 fail locally.
```

**Comment by vorburger** [comment] 2024-02-18 15:31
@teivah do you have any interest to contribute (minor) fixes to make the test pass on Mac?

PR with docs update to https://docs.enola.dev/dev/setup/ for OS X may also make sense... notably re. Xcode! (That's just so weird.. why?!)

I guess you could even add a GitHub Action for Mac, to prevent future regression.

BTW FYI the project now also has a [Development Environment in a Docker Container](https://docs.enola.dev/dev/setup/#development-environment-in-a-docker-container)... is that easier, on Mac?

**Comment by vorburger** [comment] 2024-03-24 12:43
There were 2 unrelated test failures shown above:

1. `MediaTypeDetectorTest`: That's the same as #509, which I just ran into as well, and just got fixed with #609.

1. `RunnerTest`: That's separate, and due to: _expected:<bash: [line 1: ]does-not-exist: comm...> but was:<bash: []does-not-exist: comm...>_ which is specific to Mac, or more likely due to some older/newer Bash version, or default Bash configuration on Mac. This one still needs a fix.

**Comment by vorburger** [comment] 2024-03-24 12:47
> RunnerTest: That's separate, and due to: expected:<bash: [line 1: ]does-not-exist: comm...> but was:<bash: []does-not-exist: comm...> which is specific to Mac, or more likely due to some older/newer Bash version, or default Bash configuration on Mac. This one still needs a fix.

https://github.com/enola-dev/enola/commit/ec29b29bce4a940245eafcd04e89cef6a458374a had already fixed that, actually.

@teivah do you have any interest to recheck to confirm that it now builds clean on Mac OS X Darwin?

**Comment by vorburger** [comment] 2024-12-29 22:44
Done.

**Closed by vorburger** 2024-12-29 22:44 UTC
Labels: enhancement, build, mac-only, contributors, ⏳awaiting reporter
